apiVersion: v1
kind: Service
metadata:
  name: {{ template "testdevspace.fullname" . }}-nginx
  labels:
    app: {{ template "testdevspace.fullname" . }}-nginx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: http
      nodePort: 30000
  selector:
    app: {{ template "testdevspace.fullname" . }}-nginx
